name: .NET Core Workflow

on:
  push:
    branches:
      - main
 # schedule:
 #   - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: github4women

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: github4women

    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: github4women

  custom_script:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Custom script
      run: |
        echo "Workflow realizado com sucesso!!"
